### ISSUE TITLE
Decoder missing

### ISSUE THREAD

**Issue by okseb** [flathub/org.bino3d.bino#2]
When I try and play a video I only get sound and I get the following error in the console.

`Bino: Qt warning: Warning: "No decoder available for type 'video/x-h265"`

Am I missing an extension or is this just a missing lib in the Flatpak manifest?

**Comment by marlam** [comment]
This is probably due to the set of GStreamer plugins installed in the org.kde.Platform version 6.4.

I plan to move Bino to Qt 6.5 next which uses FFmpeg instead of GStreamer; that should fix this issue (and several others).

**Comment by marlam** [comment]
Bino now uses org.kde.Platform version 6.7, which should fix this problem.
